services:
  app:
    image: flashease
    container_name: app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    environment:
      - ENVIRONMENT=docker
    ports:
      - '3001:3001'
    depends_on:
      - mysql
      - redis
    networks:
      - flashease

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - flashease
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis/redis-stack:6.2.6-v17
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis:/data
    environment:
      REDIS_ARGS: '--requirepass ${REDIS_DEFAULT_PASSWORD} --user ${REDIS_USERNAME} on >${REDIS_PASSWORD} ${REDIS_PERMISSIONS}'
    networks:
      - flashease

volumes:
  mysql:
    driver: local
  redis:
    driver: local

networks:
  flashease:
    driver: bridge
