# docker compose -f compose.local.yml up --watch --build
services:
  app:
    image: hungpn23/flashease:1.0
    container_name: app
    restart: unless-stopped
    env_file:
      - .env.docker
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./src:/app/src
    command: ['pnpm', 'start:dev']
    # develop:
    #   watch:
    #     - action: sync
    #       path: ./src
    #       target: /app/src
    #       ignore:
    #         - metadata.ts
    #     - action: rebuild
    #       path: .
    #       target: /app
    #       ignore:
    #         - src/
    depends_on:
      - mysql
      - redis
    networks:
      - flashease

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - flashease
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis/redis-stack:6.2.6-v17
    container_name: redis
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis:/data
    environment:
      REDIS_ARGS: '--requirepass ${REDIS_DEFAULT_PASSWORD} --user ${REDIS_USERNAME} on >${REDIS_PASSWORD} ${REDIS_PERMISSIONS}'
    networks:
      - flashease

volumes:
  mysql:
    driver: local
  redis:
    driver: local

networks:
  flashease:
    driver: bridge
